### ISSUE TITLE
Duplicate content on update

### ISSUE THREAD

**Issue by Glaizotm** [laluka/lalubuntu#16]
on the roles/gui_tools/tasks/setup-regolith.yml 

the block : 
_- name: Append lines to the i3 Xresources file
  ansible.builtin.blockinfile:
    path: '{{ ansible_env.HOME }}/.config/regolith3/Xresources'
    block: '{{ i3_xresources_block }}'
    marker: '! Ansible managed block'
    create: yes_

generate some dupicate line each time you launch update.sh/install.sh

It seem to work better with : 
    marker: "! {mark} ANSIBLE MANAGED BLOCK"

**Comment by laluka** [comment]
Reproduced, kind of!

I changed the comment syntax as the previous comment marker was causing errors (seen a few days ago with `journalctl -xe`, but this change made the lines different, it's not an exact copy... :/

Working on a fix! :)

**Comment by laluka** [comment]
Can you check this one out please ? :pray: 
https://github.com/laluka/lalubuntu/pull/17

**Comment by laluka** [comment]
Fixed (& reviewed :D ) by https://github.com/laluka/lalubuntu/pull/17
