### ISSUE TITLE
install s'arrete a ces lignes 

### ISSUE THREAD

**Issue by web-differently12** [laluka/lalubuntu#19]
TASK [roles/base-install : Install cargo-based tools (this will take lot of time to install)] **********
task path: /opt/lalubuntu/roles/base-install/tasks/cargo-dl.yml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: user
<127.0.0.1> EXEC /bin/sh -c 'echo ~user && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp `"&& mkdir "` echo /home/user/.ansible/tmp/ansible-tmp-1713213969.2661328-207465-87797111790613 `" && echo ansible-tmp-1713213969.2661328-207465-87797111790613="` echo /home/user/.ansible/tmp/ansible-tmp-1713213969.2661328-207465-87797111790613 `" ) && sleep 0'
Using module file /home/user/.local/pipx/venvs/ansible-core/lib/python3.10/site-packages/ansible/modules/command.py
<127.0.0.1> PUT /home/user/.ansible/tmp/ansible-local-195408i6pxl3qi/tmpn4isofwl TO /home/user/.ansible/tmp/ansible-tmp-1713213969.2661328-207465-87797111790613/AnsiballZ_command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1713213969.2661328-207465-87797111790613/ /home/user/.ansible/tmp/ansible-tmp-1713213969.2661328-207465-87797111790613/AnsiballZ_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/user/.ansible/tmp/ansible-tmp-1713213969.2661328-207465-87797111790613/AnsiballZ_command.py && sleep 0'

**Comment by web-differently12** [comment]
je l'ai refait 3 fois et maintenant ça marche, merci

**Comment by laluka** [comment]
Hello !

Parfois des soucis de réseau ou de place libre peuvent jouer, ou des indisponibilités temporaires des outils et packages managers sur lesquels se reposent nos dépendances.. :/

Tout bon du coup ? 🌹

**Comment by web-differently12** [comment]
oui merci beaucoup ça fonctione a merveille? Chapeau pour le grand travail

**Comment by laluka** [comment]
Merci et bonne soirée, hf avec ton nouvel outil/jouet ! ^_^
