### ISSUE TITLE
Error on "roles/base-install : Fix wildcard in history"

### ISSUE THREAD

**Issue by clem9669** [laluka/lalubuntu#9]
Hi @laluka,

On fresh Ubuntu, I got this error on step Fix wildcard in history: 

```sh
TASK [roles/base-install : Fix wildcard in history] *************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "zsh -c 'source /home/ubuntu/.zshrc && set mark-modified-lines off'", "delta": "0:00:00.132703", "end": "2024-01-31 16:01:58.696206", "msg": "non-zero return code", "rc": 127, "start": "2024-01-31 16:01:58.563503", "stderr": "/home/ubuntu/.zshrc:source:105: no such file or directory: /opt/lalubuntu/aliases", "stderr_lines": ["/home/ubuntu/.zshrc:source:105: no such file or directory: /opt/lalubuntu/aliases"], "stdout": "", "stdout_lines": []}

```

Cheers

**Comment by laluka** [comment]
Hi Sir !
Can you provide more detail please, like `uname -a` and `cat /etc/issue`
With the latest commit you run the install scripts on please ? 

The error `no such file or directory: /opt/lalubuntu/aliases` makes me thiiiink that you might have skipped the doc that states that the repo `lalubuntu` should be in `/opt` (optionnal softs) for the nominal behavior! :)

Doc & suggested commands : https://github.com/laluka/lalubuntu?tab=readme-ov-file#pre-install-install-update

Have a nice day! :rose: 

I

**Comment by clem9669** [comment]
My bad, I missed this bit 😶‍

Thanks @laluka 🚀
